apiVersion: ktransform.mgoltzsche.github.com/v1alpha1
kind: SecretTransform
metadata:
  name: dockertomakisuconf
spec:
  input:
    secret1:
      secret: regcred1
    secret2:
      secret: regcred2
  output:
  - secret:
      name: makisu-conf
      type: Opaque
    transformation:
      makisu.conf: |
        (.secret1[".dockerconfigjson"].object.auths * .secret2[".dockerconfigjson"].object.auths) |
          with_entries(.value |= {
            security: {
              basic: .auth | @base64d | split(":") | {
                username: .[0],
                password: .[1]
              }
            }
          })
