apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktransform-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ktransform
  template:
    metadata:
      labels:
        name: ktransform
    spec:
      serviceAccountName: ktransform
      containers:
        - name: ktransform
          image: mgoltzsche/ktransform
          command:
          - ktransform
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ktransform"
